stages:
  - name: deploy
    if: branch = master

python:
  - 3.6

# script: bundle exec rspec
script: echo pre script busk

jobs:
  include:
    - stage: deploy to staging
      python: 3.6 
      install: skip # bundle install is not required
      script: ./install.sh
    - stage: test-staging 
      python: 3.6 
      install: skip # bundle install is not required
      script: ./install.sh
    # - &test-staging
    #   stage: test staging
    #   rvm: 2.3
    #   install: skip
    #   script: ./test-staging.sh one
    # - <<: *test-staging
    #   script: ./test-staging.sh two
    # - <<: *test-staging
    #   script: ./test-staging.sh three

# stages:
#   - name: test 
#     if: branch = dev 
#

dist: bionic 
sudo: required
language: python
python:
  - "3.6"

deploy:
  python:
    - "3.6"
  provider: snap
  # snap: my_*.snap
  snap: lxd 
  # channel: edge
  channel: stable 
  skip_cleanup: true
  script:
    - ./install.sh 



        # dist: bionic
        # sudo: required
        # language: python
        # python:
        #   - "3.6"
        # script:
        #   # - sudo apt-get update 
        #   # - sudo apt-get install -y shellcheck
        #   # - shellcheck osfiles/usr/local/sbin/sftpuseradd
        #   - ./install.sh 
        #   - ./ci-test.sh 
